name: Continuous Integration

on: [push]

jobs:
  main:
    name: 'Check source and build bundles, if necessary'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: 'Install dependencies'
        run: yarn
      - name: 'Run checks'
        run: yarn format --check && yarn lint && yarn typecheck && yarn test
      - name: 'Build bundles'
        run: yarn build
      - name: 'Commit and push bundles'
        # TODO(mc, 2021-04-05): get rid of testing code
        if: ${{ github.ref == 'refs/heads/auto-build' }}
        # if: ${{ github.ref == 'refs/heads/main' }}
        env:
          USER_NAME: ${{ github.actor }}
          USER_ID: ${{ github.event.sender.id }}
        run: |
          git config user.name "$USER_NAME (GitHub Actions)"
          git config user.email "$USER_ID+$USER_NAME@users.noreply.github.com"
          git add ./*/dist/main.js
          git commit -m "chore: add bundles" || true
          git push
